# Generated by Django 3.1.1 on 2020-09-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custumer',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
